### ISSUE TITLE
Ojeado!

### ISSUE THREAD

**Issue by VeruGHub** [Julenasti/intro_tidyverse#1]
Muy chuli Chule. Nada que añadir. Los ejemplos son fáciles y claros 👍 
Me he dado cuenta que también tenía otro proyecto tuyo con un ejemplo de tidyverse que preparaste para una clase.

**Comment by Julenasti** [comment]
jajaj, sí tenía otro también pero le di un vistazo, no me gusto mucho la
estructura, e incorporé lo que me pareció interesante en este. Lo que mola
en el otro es que comparamos r base con tidyverse y eso está guay, pero
creo que para una sesión introductoria de tidyverse quizás es demasiado.
Mantengo el otro proyecto como idea futura ;)
Muchas gracias por la revisión Vero!!!
Un abrazo,
Julen

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Libre
de virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
